[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

# Pass environment variables to build phase
[variables]
REACT_APP_YOUTUBE_API_KEY = "${REACT_APP_YOUTUBE_API_KEY}"

[start]
cmd = "npm start"
